### ISSUE TITLE
Regression: mainClass property should not be mandatory

### ISSUE THREAD

**Issue by sdeleuze** [graalvm/native-build-tools#108]
This 0.9.2 regression (maybe coming from [this commit](https://github.com/graalvm/native-build-tools/commit/633c34cad8e169b832c8ccfb729ccefaed1a5535#diff-4b478e87d3e244b734743d63e08f0640211913a7973e1bb5073a7018297a2868) with a missing `@Optional`) breaks most Spring Native Gradle projects, since we set the main class via `-H:Class=` in `native-image.properties` and this is not consistent with Maven.

**Comment by melix** [comment]
Can you provide a reproducer? This doesn't look like a bug to me: the main class _is_ mandatory. It's set by convention to the application name. If you want to use something else, from a `native-image.properties` file, then it should be set as an input, or it means that your `native-image.properties` file changes wouldn't be considered as inputs to the task.

**Comment by sdeleuze** [comment]
Sure, please find attached a reproducer : [java-application.zip](https://github.com/graalvm/native-build-tools/files/6862136/java-application.zip)

In a nutshell:
 - Take one of the sample
 - Remove `mainClass.set('org.graalvm.demo.Application')` from the `application` block
 - Create a `src/main/resources/META-INF/native-image/native-image.properties` file with `Args = -H:Class=org.graalvm.demo.Application` content

From a user perspective, it is IMO clearly a bug (and a regression) because the end user should not be forced to set the main class in the `build.gradle`. 0.9.1 allowed both Maven and Gradle to not define it because it can be set via other ways, like `native-image.properties`, 0.9.2 still allows that with Maven but not with Gradle.

I don't think we need complex logic to validate that, `native-image.properties` can be in various places and if not specified at all (neither `build.gradle` or `native-image.properties`), the build will fail fast with a pretty explicit error message coming from the `native-image` compiler.

**Comment by melix** [comment]
Do you mean `native-image.properties` is a standard file recognized by `native-image`? If this documented?

**Comment by sdeleuze** [comment]
Yes, you can find more details in https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#embedding-a-configuration-file.

**Comment by melix** [comment]
I see, you are using the mechanism used for _consumers_. It seems a bit messy to do this, since you're embedding into the properties file things which are not used at runtime, not used by consumers. Basically there's an issue, since we need to make the difference between "I didn't provide a main class", which means the plugin needs to set a default value to build an image, and "I passed in a main class in a properties file". Since this file can live in any resource directory, I would actually prefer that it is passed explicitly, e.g made it explicit that there's a configuration file as an input, in which case the plugin could parse it to extract the main class name. If not, it means that for every invocation we'd have to scan the classpath to figure out if there's a native-image properties file which contains such an entry, but, IMHO, this is a bad thing to do since again this is only a concern for _building_ a native image for the final application itself, not for consumers of a library, for which this configuration file embedding was designed, afaik.

**Comment by sdeleuze** [comment]
It is potentially messy but that's how native image works today, middle-long term that could maybe evolve indeed.
Also keep in mind not all use cases of native image require a main class (shared library).
And this is a regression, and we need to provide consistency between Maven and Gradle for this kind of configuration.

For those reasons, as discussed in today meeting with the wider team and @lazar-mitrovic, we should make this `mainClass` property optional. As a second and distinct step, we could start a discussion about how to evolve native image towards a saner behavior that will allow us to implement in a better way Maven and Gradle plugins.
