### ISSUE TITLE
Native Maven Plugin fails to generate test configuration file if JUnit provider is specified

### ISSUE THREAD

**Issue by dzou** [graalvm/native-build-tools#161]
In some cases, users will explicitly specify the JUnit provider through a dependency for the surefire plugin: https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>

        <!-- Adding a dependency like this -->
        <dependencies>
          <dependency>
            <groupId>org.apache.maven.surefire</groupId>
            <artifactId>surefire-junit47</artifactId>
            <version>3.0.0-M5</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```

We noticed that if a project selects a JUnit provider through the method described in the docs, the `native-maven-plugin` will not generate a test configuration file that lists the tests to run.

```
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.7.1:test (test-native) on project google-cloud-secretmanager: Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.7.1:test failed: Test configuration file wasn't found. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

Here is a reproducer: https://github.com/dzou/surefire-dep-repro

We would also be open to workaround solutions if you might know of any.

**Comment by sbrannen** [comment]
The Maven and Gradle plugins in Native Build Tools only support tests executed via the JUnit Platform.

The is partially documented for the Gradle plugin but not really documented for the Maven plugin. In light of that, the documentation can definitely be improved.

In any case, providing a different Surefire provider will not work.

However, JUnit 4 is supported since JUnit 5 provides the `VintageTestEngine` for executing JUnit 4.12+ and JUnit 3.8.2 tests.

So if you remove the `surefire-junit47` provider and [add a dependency on the Vintage engine](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-running), your JUnit 4 based tests should be supported.

**Comment by dzou** [comment]
Ah, thank you for the clarifications. Closing.
