### ISSUE TITLE
Use @arg file for running native binaries

### ISSUE THREAD

**Issue by melix** [graalvm/native-build-tools#209]
Release 0.9.10 fixed the long classpath issue when _building_ a native image, but it didn't fix the problem when running tests, or when running the native binary.

It is extremely likely that only the Maven plugin is affected https://github.com/graalvm/native-build-tools/blob/0.9.10/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java#L141-L147

because the `test` mojo builds the native image directly with tests.

Gradle builds the native image separately so should be immune: https://github.com/melix/native-build-tools/blob/925d6ba73c7f0d6122dc0ba9b4ca8afe0d60ec18/native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/NativeRunTask.java#L76-L79

Initially reported at https://github.com/spring-projects-experimental/spring-native/issues/1486#issuecomment-1040620364

**Comment by lazar-mitrovic** [comment]
I'm not sure what this issue is about - argument file is only used for building native images.
[`NativeImageJUnitLauncher`](https://github.com/graalvm/native-build-tools/blob/master/common/junit-platform-native/src/main/java/org/graalvm/junit/platform/NativeImageJUnitLauncher.java) doesn't support `@` files, and I can't see where this would be a problem since it only consumes [3 different arguments](https://github.com/graalvm/native-build-tools/blob/ba55b180c741c469ba71192b3bd90fe9bebac087/common/junit-platform-native/src/main/java/org/graalvm/junit/platform/NativeImageJUnitLauncher.java#L98-L100).

Native Maven Plugin uses argument files for building tests by default on Windows since #247, so we should be good.

**Comment by melix** [comment]
I agree that this should be good, I'm closing this, let's create a new issue if something arises.

**Comment by human-user** [comment]
I get a similar failure message like https://github.com/spring-projects-experimental/spring-native/issues/1486.
