### ISSUE TITLE
Build fails if `java.io.tmpdir` contains a space

### ISSUE THREAD

**Issue by melix** [graalvm/native-build-tools#227]
See https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/401#issuecomment-1083747919

**Comment by lazar-mitrovic** [comment]
Since [this commit](https://github.com/graalvm/native-build-tools/pull/274/commits/150b0aaf3d00adab8519d5a8e69f97d79d267500) we are saving argument files by default inside of the project structure (under `build` or `target` depending on a build tool).

We should check it once again prior to the release, but I think that this issue is now fixed.
