### ISSUE TITLE
Add agent modes to Maven plugin

### ISSUE THREAD

**Issue by lazar-mitrovic** [graalvm/native-build-tools#260]
Similar to #230 for Gradle plugin, we should implement something similar for the Maven plugin:
```xml
<configuration>
    <agent>
        <enabled>true</enabled>
        <defaultMode>standard</defaultMode>
        <modes>
            <conditional>
                <userCodeFilterPath>path-to-filter.json</userCodeFilterPath>
                <extraFilterPath>path-to-another-filter.json</extraFilterPath>
            </conditional>
            <direct>agent-command-line</direct>
        </modes>
        <options>
            <callerFilterFiles>filter.json</callerFilterFiles>
            <accessFilterFiles>filter.json</accessFilterFiles>
            <builtinCallerFilter>true</builtinCallerFilter>
            <builtinHeuristicFilter>true</builtinHeuristicFilter>
            <enableExperimentalPredefinedClasses>false</enableExperimentalPredefinedClasses>
            <enableExperimentalUnsafeAllocationTracing>false</enableExperimentalUnsafeAllocationTracing>
            <trackReflectionMetadata>true</trackReflectionMetadata>
        </options>
        <metadataCopy>
            <disabledPhases>
            <phase>test</phase>
            </disabledPhases>
            <outputDirectory>src/main/resources/META-INF/native-image</outputDirectory>
        </metadataCopy>
    </agent>
</configuration>
```

**Comment by sdeleuze** [comment]
Concrete use case that will hopefully be solved by this issue : allowing Spring native agent sample to remove [this usage](https://github.com/spring-projects-experimental/spring-native/blob/main/samples/commandlinerunner-agent/pom.xml#L36-L56) of `maven-antrun-plugin`

Unrelated : I am quite puzzled by the DevXP people get with everything in red in the IDE :
![image](https://user-images.githubusercontent.com/141109/178479036-463360e9-58f9-4735-a06d-5b37d5bd05f5.png)

I think this is related to our usage of a Maven extension to parse the XML.

@lazar-mitrovic Could you please detail why this is needed? I would like to explore if there is a path where at least most common parts of the XML config can discoverable and not in red like that.

**Comment by alvarosanchez** [comment]
The reason why those elements are in red is because the generated `META-INF/maven/plugin.xml` has all the descriptions as `<description></description>`.

When building a Maven plugin with Maven, those are taken from the Javadoc. In the case of our Gradle-based build, I'm not sure yet what is the missing piece that makes them to be empty.

**Comment by alvarosanchez** [comment]
Sorry, I misread your comment. What I described would cause the existing config elements to not have documentation (eg by pressing F1).

`agent` in particular is in red because it's not part of `plugin.xml`, as is being read by `NativeExtension` as you described.

One possible workaround would be to add `agent` and its nested options as `@Parameter`s to any mojo (even if unused now). But probably it's not worth it since this task will precisely revamp agent configuration, and by doing so, we would need to add such `@Parameter`s

**Comment by sdeleuze** [comment]
So after the refactoring, will users have proper autocompletion and not anymore everything in red in IDEs?
