### ISSUE TITLE
[QUESTION] The doc doesn't document how to pass string args for mainclass

### ISSUE THREAD

**Issue by linghengqian** [graalvm/native-build-tools#314]
**Describe the problem**
A clear and concise description of what the problem is.
**Make sure that you have read [the documentation](https://graalvm.github.io/native-build-tools) and that you are using the latest plugin version.**

- When starting a normal jvm application, it is sometimes necessary to pass args to the mainclass.  A similar command should be something like `java -classpath "xxx.jar:xxx2.jar" com.example.Application 1 2 3`, where `1 2 3` will be passed to mainclass as three args.

- But I didn't see the introduction of incoming args in https://graalvm.github.io/native-build-tools/latest/maven-plugin.html .  I feel like it shouldn't be the `buildArgs` associated with the native image, nor is it the `jvmArgs`.  I'm wondering if I'm overlooking something in the `Configuration options`?

**Additional context**

- I don't feel the need for additional information.

**System Info (please complete the following information):**
 - OS: [e.g. `Windows`] Linux
 - GraalVM Version [e.g. `22.0 CE`] 22.2.0 CE
 - Java Version [e.g. `17`] 17
 - Plugin version [e.g. `native-gradle-plugin:0.9.10`] native-gradle-plugin:0.9.14

**To Reproduce**
If possible please attach a complete reproducer here (either as [a zip file](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to public repository/branch).

- I don't feel the need for additional information.

**Comment by linghengqian** [comment]
- I'm a GraalVM newbie, so I was a little surprised when I saw https://github.com/graalvm/game-of-life-native .  Does the process of passing args to mainclass happen after the native image is built?  Should I close this issue then?  

```
Command Line Arguments

Command line arguments are optional.

./target/game-of-life patterns/spaceship.txt 20 50 50 5 5 false true
```

**Comment by lazar-mitrovic** [comment]
When you compile a image of your java program it should behave as a drop in replacement for the `java` invocation.
That is:
```bash
java -classpath "xxx.jar:xxx2.jar" com.example.Application 1 2 3
```
should be equivalent to
```bash
./target/compiledApp 1 2 3
```

If you are using the Maven plugin, setting up the execution of the resulting image is usually done using standard `exec-maven-plugin`, as shown in `samples` here:
https://github.com/graalvm/native-build-tools/blob/dda0a59820546f93fe53ffead72359c6a394b84f/samples/java-application/pom.xml#L183-L208
You should be able to configure it in order to add arguments to the execution.

Gradle plugin on the other hand has a `nativeRun` task that can be configured using `runtimeArgs` option.
