### ISSUE TITLE
Add a check for the minimal GraalVM version

### ISSUE THREAD

**Issue by sdeleuze** [graalvm/native-build-tools#346]
In order to allow users and frameworks to deal with GraalVM compatibility explicitly and provide meaningful errors to end users, Maven and Gradle plugins should allow to specify the minimal GraalVM versions supported.

**Comment by sdeleuze** [comment]
I will focus for now on minimal version. See my proposal for the configuration bellow;

Maven
```
<configuration>
    <requireVersion>22.3</requireVersion>
</configuration>
```

Gradle
```
graalvmNative {
    requireVersion = "22.3"
}
```
For now `requireVersion` could be `MAJOR`, `MAJOR.MINOR` or `MAJOR.MINOR.PATCH` and means that the version specified and more recent will be accepted.

We can introduce later the range syntax of our choice to be able to specify upper bounds.

**Comment by melix** [comment]
What worries me, at least for Gradle, is that we're inventing a system which will interfere with the toolchain support (in other words, this belongs to the toolchain support, not the NBT configuration). I am tempted to say we should wait for the issue to be fixed by the Gradle team, so that we can reason on the "secondary" version, rather than the language version (/cc @ljacomet). Also with the merge of `native-image` in OpenJDK, I wonder if that "secondary" version will make sense in the future.

**Comment by sdeleuze** [comment]
It may not make sense when the OpenJDK integration is complete, and this is GraalVM specific so not sure Gradle toolchain should deal with that as a first class concern, but there are concrete needs for this today and next year at least.
