### ISSUE TITLE
Native build uses a lot of memory

### ISSUE THREAD

**Issue by ditogam** [graalvm/native-build-tools#494]
**Describe the problem**
We are using AWS Codebuild to make native image using with `graalvm-ce-java17-22.3.2`. CodeBuild runs on ubuntu compute type `general1.large`, which has 8 vcpu and 15 GB of memory.

`./gradlew nativeCompile`

We tried to move to new graalvm version 17.0.8, downloading from [site](https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_linux-x64_bin.tar.gz). After running the build, it failed with exit code 137. As I saw it's due to OutOfMemory.

We also tested same build on desktop pc and build memory usage exceeded 17GB.

Can you help with this issue?

Also, build generates libawt.so and other libraries in output
![image](https://github.com/graalvm/native-build-tools/assets/13191168/69efeda3-580f-4cff-8603-881356706373)

We use AWT to generate image in our app, it fails with `java.home property not set` as shown in [[native-image] java.home property not set](https://github.com/oracle/graal/issues/1812)

**System Info (please complete the following information):**
 - OS: [e.g. `Ubuntu 22.04.3 LTS`]
 - GraalVM Version [e.g. `17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14)`]
 - Java Version [e.g. `17`]
 - Plugin version [e.g. `native-gradle-plugin:0.9.25`]

**Comment by ditogam** [comment]
```
graalvmNative {
        binaries {
            main {
                buildArgs.add('-J-Xmx9g')
            }
        }
    }
```

Helped to resolved memory issue

**Comment by fniephaus** [comment]
Could you run with `--verbose` and report the value for `-XX:MaxRAMPercentage`? The `native-image` utility in that release limits itself to *available* memory at startup, so if not much memory is available, the max heap might be too small for your application. In the upcoming release (GraalVM for JDK 21), we are changing this behavior again (see https://github.com/oracle/graal/pull/7277 for impl details).

If you know that your application needs a certain amount of memory, you could also use `Xms` instead of `Xmx` to set a minimum heap, which will also bump the max heap if not more memory is available.

I hope this helps!
