### ISSUE TITLE
 Error for Gradle multi-module repo: Cannot set the value of task nativeTestBuild property 'server' of type 

### ISSUE THREAD

**Issue by xmlking** [graalvm/native-build-tools#70]
when I use 
```
plugins {
    id("org.graalvm.buildtools.native")
}
```
in multiple modules in Gradle multi-module repo, I have got following error 

```
* What went wrong:
An exception occurred applying plugin request [id: 'org.graalvm.buildtools.native', version: '0.9.0']
> Failed to apply plugin 'org.graalvm.buildtools.native'.
   > Could not create task ':apps:linking-service:nativeTestBuild'.
      > Cannot set the value of task ':apps:linking-service:nativeTestBuild' property 'server' of type org.graalvm.buildtools.gradle.NativeImageService using a provider of type org.graalvm.buildtools.gradle.NativeImageService.
```

To reproduce : https://github.com/xmlking/micro-apps

**Comment by lazar-mitrovic** [comment]
I might be missing something but I cannot reproduce this locally.

I tried invoking `./gradlew nativeBuild` in the root project, and it crashes with:
```
> Task :apps:account-service:nativeBuild FAILED
Warning: Ignoring server-mode native-image argument --no-server.
Error: Found invalid image builder Java VM argument: flag

FAILURE: Build failed with an exception.
```
This originates from wrong configuration in `apps/account-service/build.gradle.kts:78`, and removing it leads to crash due to build time initialization of slf4j.

I tried invoking `./gradlew -Pagent -DpersistConfig nativeTest` in the root project as well and it also fails with a bunch of build time initialized classes - so, due to the missing configuration.

At the end I tried running `./gradlew :apps:linking-service:nativeTest` and it resulted with crash in `compileKotlin` task, which is again unrelated to this plugin:
```
> Task :apps:linking-service:compileTestKotlin FAILED
e: micro-apps/apps/linking-service/src/test/kotlin/micro/apps/service/domain/echo/KeyingServiceTest.kt: (15, 27): Unresolved reference: KeyingService
e: micro-apps/apps/linking-service/src/test/kotlin/micro/apps/service/domain/echo/KeyingServiceTest.kt: (25, 89): Unresolved reference: KeyingService
```

Aforementioned `native-image` errors originate from `native-image` executable itself, and that invocation happens lot after the phase that would throw the stack trace like yours. 

So I would need more pointers about the command line invocation you were using in order to try to reproduce this.

**Comment by lazar-mitrovic** [comment]
@melix would you mind taking a look into this? It fails for me on `0.9.1-SNAPSHOT` with the error mentioned above, as well as using PR #71 with:
```
org.gradle.jvm.toolchain.internal.NoToolchainAvailableException: No compatible toolchains found for request filter: {languageVersion=11, vendor=matching('GraalVM'), implementation=vendor-specific} (auto-detect true, auto-download true)
```

**Comment by melix** [comment]
This is actually a bug in Gradle, see https://github.com/gradle/gradle/issues/17559

**Comment by Azbesciak** [comment]
Maybe some workaround for this? This is still an issue, I have a similar error, but I suppose the reason is the same
```
Could not create task ':my-project:collectReachabilityMetadata'.
   > Cannot set the value of task ':my-project:collectReachabilityMetadata' property 'metadataService' of type org.graalvm.buildtools.gradle.internal.GraalVMReachabilityMet
adataService using a provider of type org.graalvm.buildtools.gradle.internal.GraalVMReachabilityMetadataService.
```

**Comment by Azbesciak** [comment]
Stack trace from above in the file
[reachability_metadata.txt](https://github.com/graalvm/native-build-tools/files/10513039/reachability_metadata.txt)

I noticed that it occurs when there are multiple projects which uses that, but there is some dependency between them, and at the same time maybe others' plugins' versions differs

**Comment by w4rdy** [comment]
@Azbesciak did you ever find a solution to this? I'm experiencing the same error you were. Thanks

**Comment by Azbesciak** [comment]
@w4rdy I suppose it was because of different versions of pluggins (as mentioned); I have monorepo with multiple spring apps with shared `build.gradle` as a base, and then each has its own extension (which is optional, same to libs inside that project).
The project which is in the log was different, it was based on the spring cloud - had its own BOM, different deps.
When I made that bom shared (it was anyway adviced and common in a spring projects on initializr), also made other deps, which could have conflicts, the same, it has gone - as I remember, but it was quite a long time ago and I have a maraton of bugs and solutions to integrate spring boot native

**Comment by heruan** [comment]
I'm facing the same issue. If `id("org.graalvm.buildtools.native")` is used in more than one module, the build fails. Now Gradle discourages `allprojects` and `subprojects` and I don't want the plugin to be loaded for all subprojects. Why this happens?
